basePath: /v1
definitions:
  Memo:
    description: Memo 定义备忘录/便笺表对应的结构
    properties:
      content:
        description: 备忘录/便笺内容
        type: string
        x-go-name: Content
      created_at:
        description: 创建时间
        format: date-time
        type: string
        x-go-name: CreatedAt
      deleted_at:
        description: 删除时间
        format: date-time
        type: string
        x-go-name: DeletedAt
      id:
        description: 备忘录/便笺 ID
        format: uint64
        type: integer
        x-go-name: ID
      name:
        description: 备忘录/便笺名称
        type: string
        x-go-name: Name
      status:
        description: 备忘录/便笺状态（0正常，1归档，2回收站，3已删除）
        format: int8
        type: integer
        x-go-name: Status
      uid:
        description: 用户 ID
        format: uint64
        type: integer
        x-go-name: UID
      updated_at:
        description: 更新时间
        format: date-time
        type: string
        x-go-name: UpdatedAt
    type: object
    x-go-package: github.com/gethinyan/enterprise/models
  MemoRequestBody:
    description: MemoRequestBody 备忘录/便笺请求参数
    properties:
      content:
        description: 备忘录/便笺内容
        type: string
        x-go-name: Content
      id:
        description: 备忘录/便笺 ID（有就传）
        format: uint64
        type: integer
        x-go-name: ID
      name:
        description: 备忘录/便笺名
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/gethinyan/enterprise/models
  SignInRequestBody:
    description: SignInRequestBody 用户登录参数
    properties:
      email:
        description: 邮箱地址
        type: string
        x-go-name: Email
      password:
        description: 密码
        type: string
        x-go-name: Password
    required:
    - email
    - password
    type: object
    x-go-package: github.com/gethinyan/enterprise/api/v1
  SyncMemoRequestForm:
    description: SyncMemoRequestForm 同步备忘录/便笺表单
    properties:
      add:
        description: 新增备忘录/便笺
        items:
          $ref: '#/definitions/MemoRequestBody'
        type: array
        x-go-name: Add
      archive:
        description: 归档备忘录/便笺
        items:
          $ref: '#/definitions/MemoRequestBody'
        type: array
        x-go-name: Archive
      delete:
        description: 删除备忘录/便笺
        items:
          $ref: '#/definitions/MemoRequestBody'
        type: array
        x-go-name: Delete
      restore:
        description: 恢复备忘录/便笺
        items:
          $ref: '#/definitions/MemoRequestBody'
        type: array
        x-go-name: Restore
      update:
        description: 修改备忘录/便笺
        items:
          $ref: '#/definitions/MemoRequestBody'
        type: array
        x-go-name: Update
    type: object
    x-go-package: github.com/gethinyan/enterprise/api/v1
  UserRequestBody:
    description: UserRequestBody 用户请求参数
    properties:
      address:
        description: 地址
        type: string
        x-go-name: Address
      avatar_url:
        description: 头像地址
        type: string
        x-go-name: AvatarURL
      birth:
        description: 生日
        format: date-time
        type: string
        x-go-name: Birth
      code:
        description: 验证码（注册时必填）
        format: int64
        type: integer
        x-go-name: Code
      email:
        description: 邮箱地址
        type: string
        x-go-name: Email
      gender:
        description: 性别（0：女；1：男）
        format: int8
        type: integer
        x-go-name: Gender
      nickname:
        description: 昵称
        type: string
        x-go-name: Nickname
      password:
        description: 密码
        type: string
        x-go-name: Password
      phone:
        description: 手机号
        type: string
        x-go-name: Phone
      user_name:
        description: 用户名
        type: string
        x-go-name: Username
    required:
    - phone
    - email
    - user_name
    - password
    - gender
    type: object
    x-go-package: github.com/gethinyan/enterprise/models
  UserResponseBody:
    description: UserResponseBody 用户响应参数
    properties:
      address:
        description: 地址
        type: string
        x-go-name: Address
      avatar_url:
        description: 头像地址
        type: string
        x-go-name: AvatarURL
      birth:
        description: 生日
        format: date-time
        type: string
        x-go-name: Birth
      email:
        description: 邮箱地址
        type: string
        x-go-name: Email
      gender:
        description: 性别（0：女；1：男）
        format: int8
        type: integer
        x-go-name: Gender
      id:
        description: 用户 ID
        format: uint64
        type: integer
        x-go-name: ID
      phone:
        description: 手机号
        type: string
        x-go-name: Phone
      user_name:
        description: 用户名
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/gethinyan/enterprise/models
host: localhost:9090
info:
  contact:
    email: gethin.yan@gmail.com
    name: gethin
    url: http://notes.gethin.cn
  description: Enterprise 接口文档
  title: API.
  version: 0.0.1
paths:
  /memos:
    get:
      description: 备忘录/便笺列表
      operationId: ListMemoRequest
      responses:
        "200":
          $ref: '#/responses/ListMemoResponse'
      schemes:
      - http
      - https
  /sendEmail:
    get:
      description: 发送邮件
      operationId: sendEmailRequest
      parameters:
      - description: 邮箱地址
        in: query
        name: email
        required: true
        type: string
        x-go-name: Email
      - description: 用户名
        in: query
        name: username
        type: string
        x-go-name: Username
      responses:
        "200":
          $ref: '#/responses/SignResponse'
      schemes:
      - http
      - https
  /signIn:
    post:
      description: 用户登录
      operationId: SignInRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SignInRequestBody'
      responses:
        "200":
          $ref: '#/responses/SignResponse'
      schemes:
      - http
      - https
  /signUp:
    post:
      description: 用户注册
      operationId: SignUpRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UserRequestBody'
      responses:
        "200":
          $ref: '#/responses/SignResponse'
      schemes:
      - http
      - https
  /syncMemo:
    post:
      description: 同步备忘录/便笺
      operationId: SyncMemoRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SyncMemoRequestForm'
      responses:
        "200":
          $ref: '#/responses/SyncMemoResponse'
      schemes:
      - http
      - https
  /users/{id}:
    get:
      description: 获取用户信息
      operationId: GetUserRequest
      parameters:
      - format: uint64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/GetUserResponse'
      schemes:
      - http
      - https
    put:
      description: 更新用户信息
      operationId: UpdateUserRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/UserRequestBody'
      responses:
        "200":
          $ref: '#/responses/UpdateUserResponse'
      schemes:
      - http
      - https
responses:
  GetUserResponse:
    description: GetUserResponse 获取用户信息响应参数
    schema:
      properties:
        data:
          $ref: '#/definitions/UserResponseBody'
        message:
          description: 响应信息
          type: string
          x-go-name: Message
      type: object
  ListMemoResponse:
    description: ListMemoResponse 备忘录/便笺列表响应参数
    schema:
      properties:
        data:
          description: 备忘录/便笺列表
          items:
            $ref: '#/definitions/Memo'
          type: array
          x-go-name: Data
        message:
          description: 响应信息
          type: string
          x-go-name: Message
      type: object
  SignResponse:
    description: SignResponse 用户注册/登录响应参数
    schema:
      properties:
        data:
          $ref: '#/definitions/UserResponseBody'
        message:
          description: 响应信息
          type: string
          x-go-name: Message
      type: object
  SyncMemoResponse:
    description: SyncMemoResponse 同步备忘录/便笺响应参数
    schema:
      properties:
        data:
          description: 备忘录/便笺列表
          items:
            $ref: '#/definitions/Memo'
          type: array
          x-go-name: Data
        message:
          description: 响应信息
          type: string
          x-go-name: Message
      type: object
  UpdateUserResponse:
    description: UpdateUserResponse 修改用户响应参数
    schema:
      properties:
        data:
          $ref: '#/definitions/UserResponseBody'
        message:
          description: 响应信息
          type: string
          x-go-name: Message
      type: object
schemes:
- http
- https
swagger: "2.0"
