basePath: /v1
definitions:
  SignInForm:
    description: SignInForm 用户登录表单
    properties:
      email:
        type: string
        x-go-name: Email
      password:
        type: string
        x-go-name: Password
    type: object
    x-go-package: e.coding.net/handnote/handnote/api/v1
  SignUpForm:
    description: SignUpForm 用户注册表单
    properties:
      address:
        type: string
        x-go-name: Address
      avatar_url:
        type: string
        x-go-name: AvatarURL
      birth:
        format: date-time
        type: string
        x-go-name: Birth
      code:
        format: int64
        type: integer
        x-go-name: Code
      email:
        type: string
        x-go-name: Email
      gender:
        format: int8
        type: integer
        x-go-name: Gender
      password:
        type: string
        x-go-name: Password
      phone:
        type: string
        x-go-name: Phone
      user_name:
        type: string
        x-go-name: UserName
    type: object
    x-go-package: e.coding.net/handnote/handnote/api/v1
host: localhost:9090
info:
  contact:
    email: gethin.yan@gmail.com
    name: gethin
    url: http://notes.gethin.cn
  description: Handnote 接口文档
  title: API.
  version: 0.0.1
paths:
  /sendEmail:
    get:
      description: 发送邮件
      operationId: sendEmailRequest
      parameters:
      - in: query
        name: email
        type: string
        x-go-name: Email
      - in: query
        name: user_name
        type: string
        x-go-name: UserName
      responses:
        "200":
          $ref: '#/responses/signResponse'
      schemes:
      - http
      - https
  /signIn:
    post:
      description: 用户登录
      operationId: signInRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SignInForm'
      responses:
        "200":
          $ref: '#/responses/signResponse'
      schemes:
      - http
      - https
  /signUp:
    post:
      description: 用户注册
      operationId: signUpRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SignUpForm'
      responses:
        "200":
          $ref: '#/responses/signResponse'
      schemes:
      - http
      - https
responses:
  signResponse:
    description: SignResponse 用户注册/登录响应参数
    schema:
      properties:
        data:
          type: object
          x-go-name: Data
        message:
          type: string
          x-go-name: Message
      type: object
schemes:
- http
- https
swagger: "2.0"
