// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UserInfo
	Identity
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	ID        int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Phone     string `protobuf:"bytes,2,opt,name=Phone" json:"Phone,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=Email" json:"Email,omitempty"`
	Username  string `protobuf:"bytes,4,opt,name=Username" json:"Username,omitempty"`
	Address   string `protobuf:"bytes,5,opt,name=Address" json:"Address,omitempty"`
	Gender    int64  `protobuf:"varint,6,opt,name=Gender" json:"Gender,omitempty"`
	Birth     string `protobuf:"bytes,7,opt,name=Birth" json:"Birth,omitempty"`
	AvatarURL string `protobuf:"bytes,8,opt,name=AvatarURL" json:"AvatarURL,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserInfo) GetGender() int64 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserInfo) GetBirth() string {
	if m != nil {
		return m.Birth
	}
	return ""
}

func (m *UserInfo) GetAvatarURL() string {
	if m != nil {
		return m.AvatarURL
	}
	return ""
}

type Identity struct {
	ID int64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *Identity) Reset()                    { *m = Identity{} }
func (m *Identity) String() string            { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()               {}
func (*Identity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Identity) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "auth.UserInfo")
	proto.RegisterType((*Identity)(nil), "auth.Identity")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	GetUserInfo(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*UserInfo, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserInfo(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := grpc.Invoke(ctx, "/auth.User/GetUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	GetUserInfo(context.Context, *Identity) (*UserInfo, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.User/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2c, 0x2d, 0xc9, 0x50, 0x3a, 0xc1, 0xc8,
	0xc5, 0x11, 0x5a, 0x9c, 0x5a, 0xe4, 0x99, 0x97, 0x96, 0x2f, 0xc4, 0xc7, 0xc5, 0xe4, 0xe9, 0x22,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0xe4, 0xe9, 0x22, 0x24, 0xc2, 0xc5, 0x1a, 0x90, 0x91,
	0x9f, 0x97, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x80, 0x44, 0x5d, 0x73, 0x13,
	0x33, 0x73, 0x24, 0x98, 0x21, 0xa2, 0x60, 0x8e, 0x90, 0x14, 0xc4, 0x9c, 0xbc, 0xc4, 0xdc, 0x54,
	0x09, 0x16, 0xb0, 0x04, 0x9c, 0x2f, 0x24, 0xc1, 0xc5, 0xee, 0x98, 0x92, 0x52, 0x94, 0x5a, 0x5c,
	0x2c, 0xc1, 0x0a, 0x96, 0x82, 0x71, 0x85, 0xc4, 0xb8, 0xd8, 0xdc, 0x53, 0xf3, 0x52, 0x52, 0x8b,
	0x24, 0xd8, 0xc0, 0xb6, 0x42, 0x79, 0x20, 0x3b, 0x9c, 0x32, 0x8b, 0x4a, 0x32, 0x24, 0xd8, 0x21,
	0x76, 0x80, 0x39, 0x42, 0x32, 0x5c, 0x9c, 0x8e, 0x65, 0x89, 0x25, 0x89, 0x45, 0xa1, 0x41, 0x3e,
	0x12, 0x1c, 0x60, 0x19, 0x84, 0x80, 0x92, 0x14, 0x17, 0x87, 0x67, 0x4a, 0x6a, 0x5e, 0x49, 0x66,
	0x49, 0x25, 0xba, 0x4f, 0x8c, 0x4c, 0xb9, 0x58, 0x40, 0xae, 0x11, 0xd2, 0xe5, 0xe2, 0x76, 0x4f,
	0x2d, 0x41, 0x78, 0x58, 0x0f, 0x14, 0x08, 0x7a, 0x30, 0x6d, 0x52, 0x50, 0x3e, 0x4c, 0x3e, 0x89,
	0x0d, 0x1c, 0x54, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0x56, 0xf7, 0xcb, 0x38, 0x01,
	0x00, 0x00,
}
